site_name: Interoperability Framework
repo_url: https://github.com/Digital-Business-Council/Interoperability-Framework
pages:
    - 'Audience': 'index.md'
    - 'Disclaimer': 'disclaimer.md'
    - 'Introduction': 'introduction.md'
theme: mkdocs
